### PR TITLE
Multiple-field and ignore field search

### PR DESCRIPTION
**Pull request by subnix**
Doc ref: 
- http://sphinxsearch.com/docs/current/extended-syntax.html
- https://docs.manticoresearch.com/latest/html/searching/extended_query_syntax.html

### CODE REVIEW

**Comment by AdrielVelazquez** [comment]
@subnix Does this lib work with manticore as well? I personally haven't tested it.

**Comment by subnix** [comment]
Yes, they have the same syntax.
I use manticore and didn’t notice any problems.

**Comment by AdrielVelazquez** [comment]
@subnix I'll release a new version of the package this week. 

https://pypi.org/project/sqlalchemy-sphinx/0.9.0/

Are you using the official pypi package? If so, I can release an incremental upgrade tonight.

**Comment by subnix** [comment]
Ok.
No, I'm using private fork with these updates.

**Comment by subnix** [comment]
Also I want to improve tests.

**Pull request merged**
